version: '3.8'

services:
  whiskey-backend:
    image: whiskey-backend:latest
    container_name: whiskey-backend
    ports:
      - "10002:10002"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped