version: '3.8'

services:
  whiskey-backend:
    image: whisty-backend:latest
    container_name: whisty-backend
    ports:
      - "10006:10006"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=whiskeydb
      - DB_USERNAME=rusty
      - DB_PASSWORD=zja2592zja!@#
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src/main/resources/uploads/images:/app/src/main/resources/uploads/images
      - /home/rusty/whiskey/whisty-backend/keyfile.md:/app/keyfile.md
    restart: unless-stopped
